// generated by verbgen

public enum BiboSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://purl.org/ontology/bibo/")}
}

public enum CalSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://www.w3.org/2002/12/cal/icaltzd#")}
}

public enum CcSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://creativecommons.org/ns#")}
}

public enum DcSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://purl.org/dc/elements/1.1/")}
}

public enum DctSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://purl.org/dc/terms/")}
}

public enum DctermsSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://purl.org/dc/terms/")}
}

public enum FoafSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://xmlns.com/foaf/0.1/")}
}

public enum GeoSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://www.w3.org/2003/01/geo/wgs84_pos#")}
}

public enum GeorssSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://www.georss.org/georss")}
}

public enum GrSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://purl.org/goodrelations/v1#")}
}

public enum IcSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://imi.ipa.go.jp/ns/core/rdf#")}
}

public enum JrrkSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://purl.org/jrrk#")}
}

public enum OwlSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://www.w3.org/2002/07/owl#")}
}

public enum PcSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://purl.org/procurement/public-contracts#")}
}

public enum QbSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://purl.org/linked-data/cube#")}
}

public enum RdfSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://www.w3.org/1999/02/22-rdf-syntax-ns#")}
}

public enum RdfsSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://www.w3.org/2000/01/rdf-schema#")}
}

public enum SacSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://statdb.nstac.go.jp/lod/sac/C")}
}

public enum SacsSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://statdb.nstac.go.jp/lod/terms/sacs#")}
}

public enum SchemaSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://schema.org/")}
}

public enum SdmxConceptSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://purl.org/linked-data/sdmx/2009/concept#")}
}

public enum SdmxDimensionSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://purl.org/linked-data/sdmx/2009/dimension#")}
}

public enum SdmxMeasureSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://purl.org/linked-data/sdmx/2009/measure#")}
}

public enum SkosSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://www.w3.org/2004/02/skos/core#")}
}

public enum XsdSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://www.w3.org/2001/XMLSchema#")}
}

public enum RegSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "http://purl.org/metainfo/terms/registry#")}
}

public enum ImasSchema: IRIBaseProvider {
    public static var base: IRIRef {return IRIRef(value: "https://sparql.crssnky.xyz/imasrdf/URIs/imas-schema.ttl#")}
}
