use_frameworks!
platform :macos, '10.12'

target 'SwiftSparql_Example' do
  pod 'SwiftSparql', :path => '../'
  pod 'BrightFutures'

  target 'SwiftSparql_Tests' do
    inherit! :search_paths
  end
end
