use_frameworks!
platform :macos, '12.0'

target 'SwiftSparql_Example' do
  pod 'SwiftSparql', :path => '../'

  target 'SwiftSparql_Tests' do
    inherit! :search_paths
  end
end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      if Gem::Version.new('12.0') > Gem::Version.new(c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        c.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
