name: CI

on:
  push:
    branches: [ m@ster ]
  pull_request:
    branches: [ m@ster ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift build
  podspec:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - run: bundle update --bundler
    - run: bundle install
    - run: bundle exec pod lib lint
